default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { 'postgres://fortytools:HhmotRCStJz8ySUnH9Mn@database/geocoding_development' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'postgres://fortytools:HhmotRCStJz8ySUnH9Mn@database/geocoding_test' } %>

production:
  <<: *default
